os: osx
osx_image: xcode10.1
language: ruby
script:
  - brew install iterative/homebrew-dvc/dvc
  - dvc version
  - brew linkage dvc
  - brew test dvc
  - brew audit --strict dvc
  - brew uninstall dvc
