name: update
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Homebrew formula
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{secrets.TOKEN}}
      run: |
        git config --global user.name 'Ruslan Kuprieiev'
        git config --global user.email ruslan@iterative.ai
        brew update
        brew install pipgrip || brew link --overwrite python@3.9
        brew install dvc || brew link --overwrite gcc@8
        brew bump-formula-pr dvc --no-browse --version $(bash ./latest.sh)
