name: update
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check latest
      id: latest
      run: |
        version=$(bash ./latest.sh)
        echo "::set-output name=version::$version"
    - name: Update Homebrew formula
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{secrets.TOKEN}}
      run: |
        git config --global user.name 'Ruslan Kuprieiev'
        git config --global user.email ruslan@iterative.ai
        brew install pipgrip
        brew upgrade
        pipgrip --json --no-cache-dir dvc==1.11.9
        brew bump-formula-pr dvc --no-browse --force --version ${{ steps.latest.outputs.version }}
