name: update dvc formula
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  - name: Update Homebrew formula
    uses: dawidd6/action-homebrew-bump-formula@v3
    with:
      token: ${{secrets.TOKEN}}
      formula: dvc
      livecheck: true
