name: update
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install pipgrip
      run: brew install pipgrip
    - name: Update Homebrew formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      env:
        HOMEBREW_VERBOSE: true
      with:
        token: ${{secrets.TOKEN}}
        formula: dvc
        livecheck: true
