name: update
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check latest
      id: latest
      run: |
        version=$(bash ./latest.sh)
        echo "::set-output name=version::$version"
    - name: Update homebrew-core fork
      run: |
        git config --global user.name 'Ruslan Kuprieiev'
        git config --global user.email ruslan@iterative.ai
        git clone https://efiop:${{ secrets.TOKEN }}@github.com/efiop/homebrew-core
        cd homebrew-core
        git remote add upstream https://github.com/homebrew/homebrew-core
        git fetch upstream
        git rebase upstream/master
        git push -f https://efiop:${{ secrets.TOKEN }}@github.com/efiop/homebrew-core
    - name: Update Homebrew formula
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{secrets.TOKEN}}
      run: |
        brew install pipgrip
        brew upgrade
        pipgrip --json --no-cache-dir dvc==1.11.9
        brew bump-formula-pr dvc --no-browse --dry-run --version ${{ steps.latest.outputs.version }}
