name: update
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: macos-latest
    steps:
    - name: Check latest
      id: latest
      run: |
        version=$(brew livecheck dvc --json | jq '.[0].version.latest')
        echo "::set-output name=version::$version"
    - name: Update Homebrew formula
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{secrets.TOKEN}}
      run: |
        brew install pipgrip
        brew bump-formula-pr dvc --version ${{ steps.latest.outputs.version }}
